version: "3.9"
services:
  db:
    image: mysql:8.0.37
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: cms2      
    volumes:
      - dbdata:/var/lib/mysql
      - ./base/cms2.sql:/docker-entrypoint-initdb.d/cms2.sql
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "cms2"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "1234"
    volumes:
      - ./www:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "1234"
volumes:
  dbdata:
